myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),

]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int,
                                label=_('Quantity'))
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    if cart:
        return redirect('cart:cart_detail')
    return redirect('shop:product_list')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/detail.html',
                           {'cart': cart,
                            'coupon_apply_form': coupon_apply_form})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}

    <div class="container">

        <div class="page-title">
            <h3>{% trans "Your shopping cart" %}</h3>
        </div>

        <div class="row">

            <div class="col-sm-12 col-md-8">

                <div class="wrapper-table-cart">
                    
                    <!-- Товары для покупки -->
                    <table class="shop-table">

                        <thead>
                            <tr>
                                <th>{% trans "Image" %}</th>
                                <th>{% trans "Product" %}</th>
                                <th>{% trans "Unit price" %}</th>
                                <th>{% trans "Quantity" %}</th>
                                <th>{% trans "Price" %}</th>
                                <th>{% trans "Remove" %}</th>
                            </tr>
                        </thead>

                        <tbody>

                            {% for item in cart %}
                                {% with product=item.product %}

                                    <tr>

                                        <td>
                                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.jpg" %}{% endif %}" alt="{{ product.name }}">
                                        </td>

                                        <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>

                                        <td>{{ item.price }}</td>

                                        <td>
                                            <form class="quantity" action="{% url "cart:cart_add" product.id %}" method="post">
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <input type="submit" value="{% trans "Update" %}">
                                                {% csrf_token %}
                                            </form>
                                        </td>

                                        <td>{{ item.total_price }}</td>

                                        <td class="product-remove">
                                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                                <input type="submit" value="X">
                                                {% csrf_token %}
                                            </form>
                                        </td>

                                    </tr>

                                {% endwith %}
                            {% endfor %}

                        </tbody>

                    </table>
                    <!-- Конец блока товаров для покупки -->
               
                </div>

                <!-- Блок купонов на скидку -->
                <div class="box-coupon">

                    <h3 class="coupon-box-title">{% trans "Apply a coupon" %}:</h3>

                    <div class="inner-box">
                        <form action="{% url "coupons:apply" %}" method="post">
                            {{ coupon_apply_form }}
                            <input type="submit" class="button" name="apply_coupon" value="{% trans "Apply" %}">
                            {% csrf_token %}
                        </form>
                    </div>

                </div>
                <!-- Конец блока купонов на скидку -->

            </div>
            
            <!-- Итог по покупке -->
            <div class="col-sm-12 col-md-4">
                <div class="box-cart-total">

                    <h2 class="title">{% trans "Cart Totals" %}</h2>

                    <table>

                        <tr>
                            <td colspan="2">{% trans "Subtotal" %}:</td>
                            <td colspan="1" class="text-right">{{ cart.get_total_price|floatformat:2 }} ₽</td>
                        </tr>

                        {% if cart.coupon %}

                            <tr>
                                {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                                    <td colspan="2">"{{ code }}" coupon ({{ discount }}% off):</td>
                                {% endblocktrans %}
                                <td colspan="1" class="text-right">- {{ cart.get_discount|floatformat:2 }} ₽</td>
                            </tr>

                        {% endif %}

                        <tr>
                            <td colspan="2" class="order-total">{% trans "Total" %}:</td>
                            <td colspan="1" class="text-right order-total total-price">{{ cart.get_total_price_after_discount|floatformat:2 }} ₽</td>
                        </tr>

                    </table>

                    <a href="{% url "shop:product_list" %}" class="button medium">{% trans "Continue shopping" %}</a>
                    <a href="{% url "orders:order_create" %}" class="button checkout-button">{% trans "Checkout" %}</a>

                </div>
            </div>
            <!-- Конец блока итога по покупке -->

        </div>
    </div>

{% endblock %}